version: "3"
services:
  mvtbenchdb:
    #build:
    #  context: ./data
    image: sourcepole/mvtbenchdb:v1.2
    ports:
      - "127.0.0.1:5439:5432"

  t-rex:
    image: sourcepole/t-rex:v0.14.3
    ports:
      - "127.0.0.1:6767:6767"
    volumes:
      - ./t-rex:/var/data/in:ro
      - ./tiles:/var/data/tiles
      - ./maps:/var/data/maps:ro

  mapserver:
    # https://github.com/camptocamp/docker-mapserver/tree/7.2
    image: camptocamp/mapserver:latest
    user: www-data
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./MapServer/ne.map:/etc/mapserver/mapserver.map:ro
      - ./MapServer/epsg:/usr/share/proj/epsg:ro

  mapcache:
    # https://github.com/camptocamp/docker-mapcache
    image: camptocamp/mapcache:latest
    user: www-data
    ports:
      - "127.0.0.1:6767:8080"
    volumes:
      - ./MapServer/mapcache_mvt.xml:/etc/mapcache/mapcache.xml:ro
      - ./tiles:/var/sig/tiles

  martin:
    image: urbica/martin:latest
    command: ["martin", "--config=/config.yaml"]
    ports:
      - "127.0.0.1:3000:3080"
    volumes:
      - ./martin/config.yaml:/config.yaml:ro

  gdal:
    image: osgeo/gdal:alpine-small-latest
    volumes:
      - ./tiles:/var/data/tiles
  # docker-compose run gdal ogrinfo -al -so /var/data/tiles/ne_countries/6/34/21.pbf

  nginx-t-rex:
    image: nginx:alpine
    ports:
      - "127.0.0.1:8088:80"
    volumes:
      - ./maps/nginx-server.conf:/etc/nginx/conf.d/default.conf:ro
      - ./maps:/usr/share/nginx/html:ro
      - ./maps/tilejson-t-rex.json:/data/tiles.json:ro
      - ./tiles:/data/tiles:ro
    # docker-compose up nginx
    # xdg-open http://localhost:8088/

  nginx-ms:
    image: nginx:alpine
    ports:
      - "127.0.0.1:8088:80"
    volumes:
      - ./maps/nginx-server.conf:/etc/nginx/conf.d/default.conf:ro
      - ./maps:/usr/share/nginx/html:ro
      - ./maps/tilejson-ms.json:/data/tiles.json:ro
      - ./tiles:/data/tiles:ro
